use std::fs;
use tauri::{AppHandle, Manager, State};

use crate::db::models::SummaryType;
use crate::db::Database;

#[derive(serde::Serialize)]
pub struct ExportData {
    pub markdown: String,
    pub filename: String,
}

#[tauri::command]
pub fn export_note_markdown(
    db: State<Database>,
    note_id: String,
) -> Result<ExportData, String> {
    let conn = db.conn.lock().map_err(|e| e.to_string())?;

    // Get note
    let note: (String, Option<String>, Option<String>, String, Option<String>) = conn
        .query_row(
            "SELECT title, description, participants, started_at, ended_at FROM notes WHERE id = ?1",
            [&note_id],
            |row| Ok((row.get(0)?, row.get(1)?, row.get(2)?, row.get(3)?, row.get(4)?)),
        )
        .map_err(|e| e.to_string())?;

    let (title, description, participants, started_at, ended_at) = note;

    // Get transcripts
    let mut stmt = conn
        .prepare(
            "SELECT start_time, end_time, text FROM transcript_segments
             WHERE note_id = ?1 ORDER BY start_time ASC",
        )
        .map_err(|e| e.to_string())?;

    let transcripts: Vec<(f64, f64, String)> = stmt
        .query_map([&note_id], |row| Ok((row.get(0)?, row.get(1)?, row.get(2)?)))
        .map_err(|e| e.to_string())?
        .filter_map(|r| r.ok())
        .collect();

    // Get summaries
    let mut stmt = conn
        .prepare(
            "SELECT summary_type, content, created_at FROM summaries
             WHERE note_id = ?1 ORDER BY created_at DESC",
        )
        .map_err(|e| e.to_string())?;

    let summaries: Vec<(String, String, String)> = stmt
        .query_map([&note_id], |row| Ok((row.get(0)?, row.get(1)?, row.get(2)?)))
        .map_err(|e| e.to_string())?
        .filter_map(|r| r.ok())
        .collect();

    // Build markdown
    let mut md = String::new();

    // Title and metadata
    md.push_str(&format!("# {}\n\n", title));
    md.push_str(&format!("**Date:** {}\n", format_datetime(&started_at)));
    if let Some(end) = ended_at {
        md.push_str(&format!("**Duration:** {}\n", calculate_duration(&started_at, &end)));
    }
    if let Some(desc) = description {
        md.push_str(&format!("\n**Description:** {}\n", desc));
    }
    if let Some(parts) = participants {
        md.push_str(&format!("**Participants:** {}\n", parts));
    }
    md.push_str("\n---\n\n");

    // Summaries
    if !summaries.is_empty() {
        md.push_str("## AI Summaries\n\n");
        for (summary_type, content, _created_at) in &summaries {
            let type_label = match SummaryType::from_str(summary_type) {
                SummaryType::Overview => "Overview",
                SummaryType::ActionItems => "Action Items",
                SummaryType::KeyDecisions => "Key Decisions",
                SummaryType::Custom => "Custom Summary",
            };
            md.push_str(&format!("### {}\n\n{}\n\n", type_label, content));
        }
        md.push_str("---\n\n");
    }

    // Transcript
    if !transcripts.is_empty() {
        md.push_str("## Transcript\n\n");
        for (start, _end, text) in &transcripts {
            let timestamp = format_timestamp(*start);
            md.push_str(&format!("**[{}]** {}\n\n", timestamp, text.trim()));
        }
    }

    // Footer
    md.push_str("\n---\n\n");
    md.push_str("*Generated by Note67*\n");

    // Generate filename
    let safe_title = title
        .chars()
        .filter(|c| c.is_alphanumeric() || *c == ' ' || *c == '-' || *c == '_')
        .collect::<String>()
        .replace(' ', "_");
    let filename = format!("{}.md", safe_title);

    Ok(ExportData { markdown: md, filename })
}

#[tauri::command]
pub fn save_export_to_file(
    app: AppHandle,
    content: String,
    filename: String,
) -> Result<String, String> {
    let documents_dir = app
        .path()
        .document_dir()
        .map_err(|e| e.to_string())?;

    let export_dir = documents_dir.join("Note67");
    fs::create_dir_all(&export_dir).map_err(|e| e.to_string())?;

    let file_path = export_dir.join(&filename);
    fs::write(&file_path, content).map_err(|e| e.to_string())?;

    Ok(file_path.to_string_lossy().to_string())
}

#[tauri::command]
pub fn get_export_directory(app: AppHandle) -> Result<String, String> {
    let documents_dir = app
        .path()
        .document_dir()
        .map_err(|e| e.to_string())?;

    let export_dir = documents_dir.join("Note67");
    Ok(export_dir.to_string_lossy().to_string())
}

fn format_datetime(datetime_str: &str) -> String {
    chrono::DateTime::parse_from_rfc3339(datetime_str)
        .map(|dt| dt.format("%B %d, %Y at %H:%M").to_string())
        .unwrap_or_else(|_| datetime_str.to_string())
}

fn format_timestamp(seconds: f64) -> String {
    let total_secs = seconds as u64;
    let hours = total_secs / 3600;
    let minutes = (total_secs % 3600) / 60;
    let secs = total_secs % 60;

    if hours > 0 {
        format!("{:02}:{:02}:{:02}", hours, minutes, secs)
    } else {
        format!("{:02}:{:02}", minutes, secs)
    }
}

fn calculate_duration(start: &str, end: &str) -> String {
    let start_dt = chrono::DateTime::parse_from_rfc3339(start);
    let end_dt = chrono::DateTime::parse_from_rfc3339(end);

    match (start_dt, end_dt) {
        (Ok(s), Ok(e)) => {
            let duration = e.signed_duration_since(s);
            let hours = duration.num_hours();
            let minutes = duration.num_minutes() % 60;

            if hours > 0 {
                format!("{} hour{} {} minute{}",
                    hours,
                    if hours == 1 { "" } else { "s" },
                    minutes,
                    if minutes == 1 { "" } else { "s" }
                )
            } else {
                format!("{} minute{}", minutes, if minutes == 1 { "" } else { "s" })
            }
        }
        _ => "Unknown".to_string(),
    }
}
